<a href="https://colab.research.google.com/github/Krupa049/ANN/blob/main/DEPTH_WIDTH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3),
    )

deepnet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3),
    )

print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
widenet

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

In [4]:
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.2399, -0.6857],
        [ 0.4426, -0.0899]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.0544,  0.3441], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[0.5468, 0.2332],
        [0.4921, 0.6225]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([ 0.0117, -0.4524], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.4416,  0.5235],
        [-0.6227, -0.5099],
        [-0.6446,  0.4925]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.3566,  0.5244, -0.1747], requires_grad=True))
 


In [5]:
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)

print('%s nodes - Wide' %numNodesInWide)
print('%s nodes - Deep' %numNodesInDeep)

7 nodes - Wide
7 nodes - Deep


In [6]:
for p in widenet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.0393, -0.5344],
        [ 0.4579, -0.5842],
        [-0.6388, -0.4042],
        [ 0.5940,  0.6718]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.6075, -0.2944,  0.5140,  0.3849], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.1305, -0.0990,  0.2533,  0.4119],
        [ 0.0513,  0.2367, -0.2727,  0.0307],
        [-0.4203, -0.2657,  0.0698, -0.1520]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.4523, -0.4905, -0.4823], requires_grad=True))
 


In [8]:
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('%s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal - %s params' %nparams)

8 parameters
4 parameters
12 parameters
3 parameters


Total - 27 params


In [9]:
nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet - %s params' %nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet - %s params' %nparams)

Widenet - 27 params
Deepnet - 21 params


In [10]:
from torchsummary import summary
summary(widenet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [12]:
from torchsummary import summary
summary(deepnet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 2]               6
            Linear-2                 [-1, 1, 2]               6
            Linear-3                 [-1, 1, 3]               9
Total params: 21
Trainable params: 21
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
